# Generated by Django 3.2.4 on 2021-07-10 12:23

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210629_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='category'),
        ),
    ]
